name: Build Electron App for Windows

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Vite
        run: npm run build

      - name: Package Electron App
        run: npm run make

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: electron-windows-installer
          path: |
            out/make/**/*.exe
