name: Build Windows Executable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clean install
        run: |
          if (Test-Path node_modules) { Remove-Item -Recurse -Force node_modules }
          if (Test-Path package-lock.json) { Remove-Item -Force package-lock.json }
          npm install

      - name: Build Vite App
        run: npm run build

      - name: Package Electron App for Windows
        run: npx electron-forge package

      - name: Make Windows Executable (.exe)
        run: npx electron-forge make --platform=win32 --arch=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ficha-costo-excel-windows
          path: out/make/**/*.exe
